// RepeaterTastic Plugin API v1.
//
// A plugin is a separate process that connects to RepeaterTastic's PluginHost: over a Unix socket
// when RepeaterTastic starts it (managed), or over TCP when it runs elsewhere (attached). Every call
// carries the plugin's token in the "authorization" metadata ("Bearer <token>"). The Session stream
// must be opened first; the other calls work while it is open and are checked against the
// permissions the operator granted.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.1
// source: plugin/v1/plugin.proto

package pluginv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginHost_Session_FullMethodName       = "/repeatertastic.plugin.v1.PluginHost/Session"
	PluginHost_ListRadios_FullMethodName    = "/repeatertastic.plugin.v1.PluginHost/ListRadios"
	PluginHost_ListNodes_FullMethodName     = "/repeatertastic.plugin.v1.PluginHost/ListNodes"
	PluginHost_SendText_FullMethodName      = "/repeatertastic.plugin.v1.PluginHost/SendText"
	PluginHost_Traceroute_FullMethodName    = "/repeatertastic.plugin.v1.PluginHost/Traceroute"
	PluginHost_ListSensors_FullMethodName   = "/repeatertastic.plugin.v1.PluginHost/ListSensors"
	PluginHost_PublishSensor_FullMethodName = "/repeatertastic.plugin.v1.PluginHost/PublishSensor"
	PluginHost_GetStatus_FullMethodName     = "/repeatertastic.plugin.v1.PluginHost/GetStatus"
)

// PluginHostClient is the client API for PluginHost service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginHostClient interface {
	// Session: the plugin sends Hello first; the host answers Welcome (or closes with an error), then
	// streams events the plugin is allowed to see. The plugin sends status, logs and heartbeats.
	// Ending the stream means the plugin has stopped.
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PluginMessage, HostMessage], error)
	ListRadios(ctx context.Context, in *ListRadiosRequest, opts ...grpc.CallOption) (*ListRadiosResponse, error)
	// nodes.read
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	// messages.send: text from a radio's relay persona, within the plugin's send budget.
	SendText(ctx context.Context, in *SendTextRequest, opts ...grpc.CallOption) (*SendResponse, error)
	// traceroute.send: from the identity chosen in the plugin's "identities" settings on that radio
	// (the relay persona when none is), within the plugin's send budget.
	Traceroute(ctx context.Context, in *TracerouteRequest, opts ...grpc.CallOption) (*SendResponse, error)
	// sensors.publish: list the host's sensors, and give a reading to one of kind "push". The
	// identities it is attached to then broadcast it as their own sensor (docs/sensors.md).
	ListSensors(ctx context.Context, in *ListSensorsRequest, opts ...grpc.CallOption) (*ListSensorsResponse, error)
	PublishSensor(ctx context.Context, in *PublishSensorRequest, opts ...grpc.CallOption) (*PublishSensorResponse, error)
	// status.read: how the radios are doing right now. Radio says what a radio *is*; this says what
	// it is *doing* — the figures a dashboard, an exporter or an alert would want.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
}

type pluginHostClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginHostClient(cc grpc.ClientConnInterface) PluginHostClient {
	return &pluginHostClient{cc}
}

func (c *pluginHostClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PluginMessage, HostMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PluginHost_ServiceDesc.Streams[0], PluginHost_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PluginMessage, HostMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginHost_SessionClient = grpc.BidiStreamingClient[PluginMessage, HostMessage]

func (c *pluginHostClient) ListRadios(ctx context.Context, in *ListRadiosRequest, opts ...grpc.CallOption) (*ListRadiosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRadiosResponse)
	err := c.cc.Invoke(ctx, PluginHost_ListRadios_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginHostClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, PluginHost_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginHostClient) SendText(ctx context.Context, in *SendTextRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, PluginHost_SendText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginHostClient) Traceroute(ctx context.Context, in *TracerouteRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, PluginHost_Traceroute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginHostClient) ListSensors(ctx context.Context, in *ListSensorsRequest, opts ...grpc.CallOption) (*ListSensorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSensorsResponse)
	err := c.cc.Invoke(ctx, PluginHost_ListSensors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginHostClient) PublishSensor(ctx context.Context, in *PublishSensorRequest, opts ...grpc.CallOption) (*PublishSensorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishSensorResponse)
	err := c.cc.Invoke(ctx, PluginHost_PublishSensor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginHostClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, PluginHost_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginHostServer is the server API for PluginHost service.
// All implementations must embed UnimplementedPluginHostServer
// for forward compatibility.
type PluginHostServer interface {
	// Session: the plugin sends Hello first; the host answers Welcome (or closes with an error), then
	// streams events the plugin is allowed to see. The plugin sends status, logs and heartbeats.
	// Ending the stream means the plugin has stopped.
	Session(grpc.BidiStreamingServer[PluginMessage, HostMessage]) error
	ListRadios(context.Context, *ListRadiosRequest) (*ListRadiosResponse, error)
	// nodes.read
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	// messages.send: text from a radio's relay persona, within the plugin's send budget.
	SendText(context.Context, *SendTextRequest) (*SendResponse, error)
	// traceroute.send: from the identity chosen in the plugin's "identities" settings on that radio
	// (the relay persona when none is), within the plugin's send budget.
	Traceroute(context.Context, *TracerouteRequest) (*SendResponse, error)
	// sensors.publish: list the host's sensors, and give a reading to one of kind "push". The
	// identities it is attached to then broadcast it as their own sensor (docs/sensors.md).
	ListSensors(context.Context, *ListSensorsRequest) (*ListSensorsResponse, error)
	PublishSensor(context.Context, *PublishSensorRequest) (*PublishSensorResponse, error)
	// status.read: how the radios are doing right now. Radio says what a radio *is*; this says what
	// it is *doing* — the figures a dashboard, an exporter or an alert would want.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	mustEmbedUnimplementedPluginHostServer()
}

// UnimplementedPluginHostServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginHostServer struct{}

func (UnimplementedPluginHostServer) Session(grpc.BidiStreamingServer[PluginMessage, HostMessage]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedPluginHostServer) ListRadios(context.Context, *ListRadiosRequest) (*ListRadiosResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRadios not implemented")
}
func (UnimplementedPluginHostServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedPluginHostServer) SendText(context.Context, *SendTextRequest) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendText not implemented")
}
func (UnimplementedPluginHostServer) Traceroute(context.Context, *TracerouteRequest) (*SendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Traceroute not implemented")
}
func (UnimplementedPluginHostServer) ListSensors(context.Context, *ListSensorsRequest) (*ListSensorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSensors not implemented")
}
func (UnimplementedPluginHostServer) PublishSensor(context.Context, *PublishSensorRequest) (*PublishSensorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishSensor not implemented")
}
func (UnimplementedPluginHostServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedPluginHostServer) mustEmbedUnimplementedPluginHostServer() {}
func (UnimplementedPluginHostServer) testEmbeddedByValue()                    {}

// UnsafePluginHostServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginHostServer will
// result in compilation errors.
type UnsafePluginHostServer interface {
	mustEmbedUnimplementedPluginHostServer()
}

func RegisterPluginHostServer(s grpc.ServiceRegistrar, srv PluginHostServer) {
	// If the following call panics, it indicates UnimplementedPluginHostServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginHost_ServiceDesc, srv)
}

func _PluginHost_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PluginHostServer).Session(&grpc.GenericServerStream[PluginMessage, HostMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PluginHost_SessionServer = grpc.BidiStreamingServer[PluginMessage, HostMessage]

func _PluginHost_ListRadios_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRadiosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHostServer).ListRadios(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHost_ListRadios_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHostServer).ListRadios(ctx, req.(*ListRadiosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginHost_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHostServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHost_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHostServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginHost_SendText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHostServer).SendText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHost_SendText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHostServer).SendText(ctx, req.(*SendTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginHost_Traceroute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TracerouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHostServer).Traceroute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHost_Traceroute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHostServer).Traceroute(ctx, req.(*TracerouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginHost_ListSensors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSensorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHostServer).ListSensors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHost_ListSensors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHostServer).ListSensors(ctx, req.(*ListSensorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginHost_PublishSensor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishSensorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHostServer).PublishSensor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHost_PublishSensor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHostServer).PublishSensor(ctx, req.(*PublishSensorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginHost_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginHostServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginHost_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginHostServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginHost_ServiceDesc is the grpc.ServiceDesc for PluginHost service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginHost_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "repeatertastic.plugin.v1.PluginHost",
	HandlerType: (*PluginHostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListRadios",
			Handler:    _PluginHost_ListRadios_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _PluginHost_ListNodes_Handler,
		},
		{
			MethodName: "SendText",
			Handler:    _PluginHost_SendText_Handler,
		},
		{
			MethodName: "Traceroute",
			Handler:    _PluginHost_Traceroute_Handler,
		},
		{
			MethodName: "ListSensors",
			Handler:    _PluginHost_ListSensors_Handler,
		},
		{
			MethodName: "PublishSensor",
			Handler:    _PluginHost_PublishSensor_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _PluginHost_GetStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _PluginHost_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "plugin/v1/plugin.proto",
}
