// RepeaterTastic Plugin API v1.
//
// A plugin is a separate process that connects to RepeaterTastic's PluginHost: over a Unix socket
// when RepeaterTastic starts it (managed), or over TCP when it runs elsewhere (attached). Every call
// carries the plugin's token in the "authorization" metadata ("Bearer <token>"). The Session stream
// must be opened first; the other calls work while it is open and are checked against the
// permissions the operator granted.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: plugin/v1/plugin.proto

package pluginv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*PluginMessage_Hello
	//	*PluginMessage_Status
	//	*PluginMessage_Log
	//	*PluginMessage_Heartbeat
	//	*PluginMessage_Panel
	Msg           isPluginMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginMessage) Reset() {
	*x = PluginMessage{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginMessage) ProtoMessage() {}

func (x *PluginMessage) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginMessage.ProtoReflect.Descriptor instead.
func (*PluginMessage) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *PluginMessage) GetMsg() isPluginMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *PluginMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*PluginMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *PluginMessage) GetStatus() *Status {
	if x != nil {
		if x, ok := x.Msg.(*PluginMessage_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *PluginMessage) GetLog() *LogLine {
	if x != nil {
		if x, ok := x.Msg.(*PluginMessage_Log); ok {
			return x.Log
		}
	}
	return nil
}

func (x *PluginMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*PluginMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *PluginMessage) GetPanel() *PanelData {
	if x != nil {
		if x, ok := x.Msg.(*PluginMessage_Panel); ok {
			return x.Panel
		}
	}
	return nil
}

type isPluginMessage_Msg interface {
	isPluginMessage_Msg()
}

type PluginMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type PluginMessage_Status struct {
	Status *Status `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

type PluginMessage_Log struct {
	Log *LogLine `protobuf:"bytes,3,opt,name=log,proto3,oneof"`
}

type PluginMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

type PluginMessage_Panel struct {
	Panel *PanelData `protobuf:"bytes,5,opt,name=panel,proto3,oneof"`
}

func (*PluginMessage_Hello) isPluginMessage_Msg() {}

func (*PluginMessage_Status) isPluginMessage_Msg() {}

func (*PluginMessage_Log) isPluginMessage_Msg() {}

func (*PluginMessage_Heartbeat) isPluginMessage_Msg() {}

func (*PluginMessage_Panel) isPluginMessage_Msg() {}

type HostMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*HostMessage_Welcome
	//	*HostMessage_Packet
	//	*HostMessage_Node
	//	*HostMessage_Text
	//	*HostMessage_Traceroute
	//	*HostMessage_Settings
	//	*HostMessage_Stop
	//	*HostMessage_Action
	//	*HostMessage_StatusEvent
	Msg           isHostMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostMessage) Reset() {
	*x = HostMessage{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostMessage) ProtoMessage() {}

func (x *HostMessage) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostMessage.ProtoReflect.Descriptor instead.
func (*HostMessage) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *HostMessage) GetMsg() isHostMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *HostMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Msg.(*HostMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *HostMessage) GetPacket() *PacketEvent {
	if x != nil {
		if x, ok := x.Msg.(*HostMessage_Packet); ok {
			return x.Packet
		}
	}
	return nil
}

func (x *HostMessage) GetNode() *NodeEvent {
	if x != nil {
		if x, ok := x.Msg.(*HostMessage_Node); ok {
			return x.Node
		}
	}
	return nil
}

func (x *HostMessage) GetText() *TextMessageEvent {
	if x != nil {
		if x, ok := x.Msg.(*HostMessage_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *HostMessage) GetTraceroute() *TracerouteEvent {
	if x != nil {
		if x, ok := x.Msg.(*HostMessage_Traceroute); ok {
			return x.Traceroute
		}
	}
	return nil
}

func (x *HostMessage) GetSettings() *SettingsChanged {
	if x != nil {
		if x, ok := x.Msg.(*HostMessage_Settings); ok {
			return x.Settings
		}
	}
	return nil
}

func (x *HostMessage) GetStop() *Stop {
	if x != nil {
		if x, ok := x.Msg.(*HostMessage_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *HostMessage) GetAction() *PanelAction {
	if x != nil {
		if x, ok := x.Msg.(*HostMessage_Action); ok {
			return x.Action
		}
	}
	return nil
}

func (x *HostMessage) GetStatusEvent() *StatusEvent {
	if x != nil {
		if x, ok := x.Msg.(*HostMessage_StatusEvent); ok {
			return x.StatusEvent
		}
	}
	return nil
}

type isHostMessage_Msg interface {
	isHostMessage_Msg()
}

type HostMessage_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type HostMessage_Packet struct {
	Packet *PacketEvent `protobuf:"bytes,2,opt,name=packet,proto3,oneof"`
}

type HostMessage_Node struct {
	Node *NodeEvent `protobuf:"bytes,3,opt,name=node,proto3,oneof"`
}

type HostMessage_Text struct {
	Text *TextMessageEvent `protobuf:"bytes,4,opt,name=text,proto3,oneof"`
}

type HostMessage_Traceroute struct {
	Traceroute *TracerouteEvent `protobuf:"bytes,5,opt,name=traceroute,proto3,oneof"`
}

type HostMessage_Settings struct {
	Settings *SettingsChanged `protobuf:"bytes,6,opt,name=settings,proto3,oneof"`
}

type HostMessage_Stop struct {
	Stop *Stop `protobuf:"bytes,7,opt,name=stop,proto3,oneof"`
}

type HostMessage_Action struct {
	Action *PanelAction `protobuf:"bytes,8,opt,name=action,proto3,oneof"`
}

type HostMessage_StatusEvent struct {
	StatusEvent *StatusEvent `protobuf:"bytes,9,opt,name=status_event,json=statusEvent,proto3,oneof"`
}

func (*HostMessage_Welcome) isHostMessage_Msg() {}

func (*HostMessage_Packet) isHostMessage_Msg() {}

func (*HostMessage_Node) isHostMessage_Msg() {}

func (*HostMessage_Text) isHostMessage_Msg() {}

func (*HostMessage_Traceroute) isHostMessage_Msg() {}

func (*HostMessage_Settings) isHostMessage_Msg() {}

func (*HostMessage_Stop) isHostMessage_Msg() {}

func (*HostMessage_Action) isHostMessage_Msg() {}

func (*HostMessage_StatusEvent) isHostMessage_Msg() {}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	ApiVersion    uint32                 `protobuf:"varint,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"` // 1
	PluginVersion string                 `protobuf:"bytes,3,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	// An attached plugin (no bundle) may send its plugin.yaml so the GUI can show its name, logo URL,
	// permissions and settings form. Managed plugins leave it empty: their bundle has one.
	ManifestYaml  string `protobuf:"bytes,4,opt,name=manifest_yaml,json=manifestYaml,proto3" json:"manifest_yaml,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *Hello) GetApiVersion() uint32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *Hello) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

func (x *Hello) GetManifestYaml() string {
	if x != nil {
		return x.ManifestYaml
	}
	return ""
}

type Welcome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiVersion    uint32                 `protobuf:"varint,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	HostVersion   string                 `protobuf:"bytes,2,opt,name=host_version,json=hostVersion,proto3" json:"host_version,omitempty"`
	Permissions   []string               `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`                       // granted
	SettingsJson  string                 `protobuf:"bytes,4,opt,name=settings_json,json=settingsJson,proto3" json:"settings_json,omitempty"` // the plugin's settings, secrets included
	Radios        []*Radio               `protobuf:"bytes,5,rep,name=radios,proto3" json:"radios,omitempty"`
	DataDir       string                 `protobuf:"bytes,6,opt,name=data_dir,json=dataDir,proto3" json:"data_dir,omitempty"` // a folder the plugin may write to (managed plugins)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *Welcome) GetApiVersion() uint32 {
	if x != nil {
		return x.ApiVersion
	}
	return 0
}

func (x *Welcome) GetHostVersion() string {
	if x != nil {
		return x.HostVersion
	}
	return ""
}

func (x *Welcome) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Welcome) GetSettingsJson() string {
	if x != nil {
		return x.SettingsJson
	}
	return ""
}

func (x *Welcome) GetRadios() []*Radio {
	if x != nil {
		return x.Radios
	}
	return nil
}

func (x *Welcome) GetDataDir() string {
	if x != nil {
		return x.DataDir
	}
	return ""
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`                                                                         // one line shown on the plugin's card, e.g. "API connected"
	Fields        map[string]string      `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // shown as label: value pairs
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`                                                                             // "ok", "warning" or "error"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *Status) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *Status) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Status) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type LogLine struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"` // debug, info, warn, error
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogLine) Reset() {
	*x = LogLine{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogLine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogLine) ProtoMessage() {}

func (x *LogLine) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogLine.ProtoReflect.Descriptor instead.
func (*LogLine) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *LogLine) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogLine) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

// PanelData: JSON for the plugin's own GUI panel, if it has one. The panel receives the latest
// value (window message {type: "data", data}) whenever it changes and when it opens.
type PanelData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanelData) Reset() {
	*x = PanelData{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanelData) ProtoMessage() {}

func (x *PanelData) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanelData.ProtoReflect.Descriptor instead.
func (*PanelData) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *PanelData) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

// PanelAction: the plugin's panel posted {type: "action", name, payload} to the GUI.
type PanelAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanelAction) Reset() {
	*x = PanelAction{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanelAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanelAction) ProtoMessage() {}

func (x *PanelAction) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanelAction.ProtoReflect.Descriptor instead.
func (*PanelAction) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *PanelAction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PanelAction) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type SettingsChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettingsJson  string                 `protobuf:"bytes,1,opt,name=settings_json,json=settingsJson,proto3" json:"settings_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsChanged) Reset() {
	*x = SettingsChanged{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsChanged) ProtoMessage() {}

func (x *SettingsChanged) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsChanged.ProtoReflect.Descriptor instead.
func (*SettingsChanged) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *SettingsChanged) GetSettingsJson() string {
	if x != nil {
		return x.SettingsJson
	}
	return ""
}

type Stop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stop) Reset() {
	*x = Stop{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stop) ProtoMessage() {}

func (x *Stop) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stop.ProtoReflect.Descriptor instead.
func (*Stop) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *Stop) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Radio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // "main", "mf", ...
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`                           // "EU_868"
	Preset        string                 `protobuf:"bytes,4,opt,name=preset,proto3" json:"preset,omitempty"`                           // "LONG_FAST"
	PresetName    string                 `protobuf:"bytes,5,opt,name=preset_name,json=presetName,proto3" json:"preset_name,omitempty"` // "LongFast"
	FrequencyMhz  float64                `protobuf:"fixed64,6,opt,name=frequency_mhz,json=frequencyMhz,proto3" json:"frequency_mhz,omitempty"`
	Connected     bool                   `protobuf:"varint,7,opt,name=connected,proto3" json:"connected,omitempty"`
	Relay         *Identity              `protobuf:"bytes,8,opt,name=relay,proto3" json:"relay,omitempty"`           // the radio's relay persona
	Identities    []*Identity            `protobuf:"bytes,9,rep,name=identities,proto3" json:"identities,omitempty"` // every identity on the radio, the relay persona first
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Radio) Reset() {
	*x = Radio{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Radio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Radio) ProtoMessage() {}

func (x *Radio) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Radio.ProtoReflect.Descriptor instead.
func (*Radio) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *Radio) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Radio) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Radio) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Radio) GetPreset() string {
	if x != nil {
		return x.Preset
	}
	return ""
}

func (x *Radio) GetPresetName() string {
	if x != nil {
		return x.PresetName
	}
	return ""
}

func (x *Radio) GetFrequencyMhz() float64 {
	if x != nil {
		return x.FrequencyMhz
	}
	return 0
}

func (x *Radio) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *Radio) GetRelay() *Identity {
	if x != nil {
		return x.Relay
	}
	return nil
}

func (x *Radio) GetIdentities() []*Identity {
	if x != nil {
		return x.Identities
	}
	return nil
}

// RadioStatus is a radio's live figures. Counters are totals since the daemon started, so a
// consumer should treat them as monotonic and diff them rather than reading them as rates.
type RadioStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RadioId         string                 `protobuf:"bytes,1,opt,name=radio_id,json=radioId,proto3" json:"radio_id,omitempty"`
	Connected       bool                   `protobuf:"varint,2,opt,name=connected,proto3" json:"connected,omitempty"` // the modem is up and configured
	NoiseFloorDbm   int32                  `protobuf:"varint,3,opt,name=noise_floor_dbm,json=noiseFloorDbm,proto3" json:"noise_floor_dbm,omitempty"`
	AirtimeTxPct    float64                `protobuf:"fixed64,4,opt,name=airtime_tx_pct,json=airtimeTxPct,proto3" json:"airtime_tx_pct,omitempty"` // of the last hour
	DutyLimitPct    float64                `protobuf:"fixed64,5,opt,name=duty_limit_pct,json=dutyLimitPct,proto3" json:"duty_limit_pct,omitempty"` // the region's limit, or the configured override
	ChannelUtilPct  float64                `protobuf:"fixed64,6,opt,name=channel_util_pct,json=channelUtilPct,proto3" json:"channel_util_pct,omitempty"`
	Queue           uint32                 `protobuf:"varint,7,opt,name=queue,proto3" json:"queue,omitempty"` // packets waiting to transmit
	Rx              uint64                 `protobuf:"varint,8,opt,name=rx,proto3" json:"rx,omitempty"`
	Tx              uint64                 `protobuf:"varint,9,opt,name=tx,proto3" json:"tx,omitempty"`
	RxDupe          uint64                 `protobuf:"varint,10,opt,name=rx_dupe,json=rxDupe,proto3" json:"rx_dupe,omitempty"`
	RxUndecryptable uint64                 `protobuf:"varint,11,opt,name=rx_undecryptable,json=rxUndecryptable,proto3" json:"rx_undecryptable,omitempty"`
	RxBad           uint64                 `protobuf:"varint,12,opt,name=rx_bad,json=rxBad,proto3" json:"rx_bad,omitempty"`
	TxFailed        uint64                 `protobuf:"varint,13,opt,name=tx_failed,json=txFailed,proto3" json:"tx_failed,omitempty"`
	AckOk           uint64                 `protobuf:"varint,14,opt,name=ack_ok,json=ackOk,proto3" json:"ack_ok,omitempty"`
	AckFail         uint64                 `protobuf:"varint,15,opt,name=ack_fail,json=ackFail,proto3" json:"ack_fail,omitempty"`
	DroppedDuty     uint64                 `protobuf:"varint,16,opt,name=dropped_duty,json=droppedDuty,proto3" json:"dropped_duty,omitempty"`
	UptimeS         int64                  `protobuf:"varint,17,opt,name=uptime_s,json=uptimeS,proto3" json:"uptime_s,omitempty"`
	NodesHeard      uint32                 `protobuf:"varint,18,opt,name=nodes_heard,json=nodesHeard,proto3" json:"nodes_heard,omitempty"` // heard in the last two hours
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RadioStatus) Reset() {
	*x = RadioStatus{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RadioStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RadioStatus) ProtoMessage() {}

func (x *RadioStatus) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RadioStatus.ProtoReflect.Descriptor instead.
func (*RadioStatus) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *RadioStatus) GetRadioId() string {
	if x != nil {
		return x.RadioId
	}
	return ""
}

func (x *RadioStatus) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *RadioStatus) GetNoiseFloorDbm() int32 {
	if x != nil {
		return x.NoiseFloorDbm
	}
	return 0
}

func (x *RadioStatus) GetAirtimeTxPct() float64 {
	if x != nil {
		return x.AirtimeTxPct
	}
	return 0
}

func (x *RadioStatus) GetDutyLimitPct() float64 {
	if x != nil {
		return x.DutyLimitPct
	}
	return 0
}

func (x *RadioStatus) GetChannelUtilPct() float64 {
	if x != nil {
		return x.ChannelUtilPct
	}
	return 0
}

func (x *RadioStatus) GetQueue() uint32 {
	if x != nil {
		return x.Queue
	}
	return 0
}

func (x *RadioStatus) GetRx() uint64 {
	if x != nil {
		return x.Rx
	}
	return 0
}

func (x *RadioStatus) GetTx() uint64 {
	if x != nil {
		return x.Tx
	}
	return 0
}

func (x *RadioStatus) GetRxDupe() uint64 {
	if x != nil {
		return x.RxDupe
	}
	return 0
}

func (x *RadioStatus) GetRxUndecryptable() uint64 {
	if x != nil {
		return x.RxUndecryptable
	}
	return 0
}

func (x *RadioStatus) GetRxBad() uint64 {
	if x != nil {
		return x.RxBad
	}
	return 0
}

func (x *RadioStatus) GetTxFailed() uint64 {
	if x != nil {
		return x.TxFailed
	}
	return 0
}

func (x *RadioStatus) GetAckOk() uint64 {
	if x != nil {
		return x.AckOk
	}
	return 0
}

func (x *RadioStatus) GetAckFail() uint64 {
	if x != nil {
		return x.AckFail
	}
	return 0
}

func (x *RadioStatus) GetDroppedDuty() uint64 {
	if x != nil {
		return x.DroppedDuty
	}
	return 0
}

func (x *RadioStatus) GetUptimeS() int64 {
	if x != nil {
		return x.UptimeS
	}
	return 0
}

func (x *RadioStatus) GetNodesHeard() uint32 {
	if x != nil {
		return x.NodesHeard
	}
	return 0
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RadioId       string                 `protobuf:"bytes,1,opt,name=radio_id,json=radioId,proto3" json:"radio_id,omitempty"` // "" = every radio
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *GetStatusRequest) GetRadioId() string {
	if x != nil {
		return x.RadioId
	}
	return ""
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Radios        []*RadioStatus         `protobuf:"bytes,1,rep,name=radios,proto3" json:"radios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *GetStatusResponse) GetRadios() []*RadioStatus {
	if x != nil {
		return x.Radios
	}
	return nil
}

// StatusEvent arrives on the session stream for plugins holding status.read, every 30 seconds,
// so a publisher does not have to poll.
type StatusEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Radios        []*RadioStatus         `protobuf:"bytes,1,rep,name=radios,proto3" json:"radios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusEvent) Reset() {
	*x = StatusEvent{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEvent) ProtoMessage() {}

func (x *StatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEvent.ProtoReflect.Descriptor instead.
func (*StatusEvent) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *StatusEvent) GetRadios() []*RadioStatus {
	if x != nil {
		return x.Radios
	}
	return nil
}

type Identity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // "!a1c40e07"
	NodeNum       uint32                 `protobuf:"varint,2,opt,name=node_num,json=nodeNum,proto3" json:"node_num,omitempty"`
	LongName      string                 `protobuf:"bytes,3,opt,name=long_name,json=longName,proto3" json:"long_name,omitempty"`
	ShortName     string                 `protobuf:"bytes,4,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	RadioId       string                 `protobuf:"bytes,5,opt,name=radio_id,json=radioId,proto3" json:"radio_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Identity) Reset() {
	*x = Identity{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Identity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Identity) ProtoMessage() {}

func (x *Identity) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Identity.ProtoReflect.Descriptor instead.
func (*Identity) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *Identity) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Identity) GetNodeNum() uint32 {
	if x != nil {
		return x.NodeNum
	}
	return 0
}

func (x *Identity) GetLongName() string {
	if x != nil {
		return x.LongName
	}
	return ""
}

func (x *Identity) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *Identity) GetRadioId() string {
	if x != nil {
		return x.RadioId
	}
	return ""
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeNum       uint32                 `protobuf:"varint,1,opt,name=node_num,json=nodeNum,proto3" json:"node_num,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RadioId       string                 `protobuf:"bytes,3,opt,name=radio_id,json=radioId,proto3" json:"radio_id,omitempty"`
	User          []byte                 `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`                                        // meshtastic.User protobuf, when known
	Position      []byte                 `protobuf:"bytes,5,opt,name=position,proto3" json:"position,omitempty"`                                // meshtastic.Position protobuf, when known
	DeviceMetrics []byte                 `protobuf:"bytes,6,opt,name=device_metrics,json=deviceMetrics,proto3" json:"device_metrics,omitempty"` // meshtastic.DeviceMetrics protobuf, when known
	LastHeardMs   int64                  `protobuf:"varint,7,opt,name=last_heard_ms,json=lastHeardMs,proto3" json:"last_heard_ms,omitempty"`
	Snr           float32                `protobuf:"fixed32,8,opt,name=snr,proto3" json:"snr,omitempty"`
	Rssi          int32                  `protobuf:"varint,9,opt,name=rssi,proto3" json:"rssi,omitempty"`
	HopsAway      int32                  `protobuf:"varint,10,opt,name=hops_away,json=hopsAway,proto3" json:"hops_away,omitempty"` // -1 unknown
	ViaMqtt       bool                   `protobuf:"varint,11,opt,name=via_mqtt,json=viaMqtt,proto3" json:"via_mqtt,omitempty"`
	Local         bool                   `protobuf:"varint,12,opt,name=local,proto3" json:"local,omitempty"` // one of RepeaterTastic's own identities
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *Node) GetNodeNum() uint32 {
	if x != nil {
		return x.NodeNum
	}
	return 0
}

func (x *Node) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Node) GetRadioId() string {
	if x != nil {
		return x.RadioId
	}
	return ""
}

func (x *Node) GetUser() []byte {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *Node) GetPosition() []byte {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Node) GetDeviceMetrics() []byte {
	if x != nil {
		return x.DeviceMetrics
	}
	return nil
}

func (x *Node) GetLastHeardMs() int64 {
	if x != nil {
		return x.LastHeardMs
	}
	return 0
}

func (x *Node) GetSnr() float32 {
	if x != nil {
		return x.Snr
	}
	return 0
}

func (x *Node) GetRssi() int32 {
	if x != nil {
		return x.Rssi
	}
	return 0
}

func (x *Node) GetHopsAway() int32 {
	if x != nil {
		return x.HopsAway
	}
	return 0
}

func (x *Node) GetViaMqtt() bool {
	if x != nil {
		return x.ViaMqtt
	}
	return false
}

func (x *Node) GetLocal() bool {
	if x != nil {
		return x.Local
	}
	return false
}

// PacketEvent: a packet a radio received or transmitted (packets.read).
type PacketEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RadioId   string                 `protobuf:"bytes,1,opt,name=radio_id,json=radioId,proto3" json:"radio_id,omitempty"`
	Direction string                 `protobuf:"bytes,2,opt,name=direction,proto3" json:"direction,omitempty"` // "rx" or "tx"
	// How RepeaterTastic handled it. rx: heard (decoded, not for us), delivered (to one of our
	// identities), relayed, dup (seen before), echo (our own packet repeated back), legacy
	// (pre-2.3 firmware, ignored), undecryptable, bad. tx: ours, relayed.
	Kind string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	// meshtastic.MeshPacket protobuf. Decoded (payload variant "decoded") when a channel or PKI key
	// this radio holds could read it, otherwise encrypted exactly as heard. rx_time, rx_snr,
	// rx_rssi, hop_limit, hop_start, via_mqtt, relay_node and next_hop are filled.
	MeshPacket  []byte `protobuf:"bytes,4,opt,name=mesh_packet,json=meshPacket,proto3" json:"mesh_packet,omitempty"`
	Decoded     bool   `protobuf:"varint,5,opt,name=decoded,proto3" json:"decoded,omitempty"`
	ChannelHash uint32 `protobuf:"varint,6,opt,name=channel_hash,json=channelHash,proto3" json:"channel_hash,omitempty"` // the on-air channel hash (0 for a PKI DM)
	ChannelName string `protobuf:"bytes,7,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`  // the channel it decoded on, "PKI" for a DM, "" when undecoded
	TimeMs      int64  `protobuf:"varint,8,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	// The node that reports this packet: the radio's relay persona.
	ReporterNodeNum uint32 `protobuf:"varint,9,opt,name=reporter_node_num,json=reporterNodeNum,proto3" json:"reporter_node_num,omitempty"`
	// The channel's index on the relay persona (0-7), or -1 when the relay persona doesn't hold
	// the channel. When it is set, mesh_packet.channel is that index; otherwise it is the on-air hash.
	RelayChannelIndex int32 `protobuf:"varint,10,opt,name=relay_channel_index,json=relayChannelIndex,proto3" json:"relay_channel_index,omitempty"`
	// Every identity on this radio that would hear the packet as a node does: those holding the
	// channel (with its index on each), or the recipient of a DM (index 0). Empty when undecoded.
	Holders       []*ChannelHolder `protobuf:"bytes,11,rep,name=holders,proto3" json:"holders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PacketEvent) Reset() {
	*x = PacketEvent{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PacketEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketEvent) ProtoMessage() {}

func (x *PacketEvent) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketEvent.ProtoReflect.Descriptor instead.
func (*PacketEvent) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *PacketEvent) GetRadioId() string {
	if x != nil {
		return x.RadioId
	}
	return ""
}

func (x *PacketEvent) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *PacketEvent) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PacketEvent) GetMeshPacket() []byte {
	if x != nil {
		return x.MeshPacket
	}
	return nil
}

func (x *PacketEvent) GetDecoded() bool {
	if x != nil {
		return x.Decoded
	}
	return false
}

func (x *PacketEvent) GetChannelHash() uint32 {
	if x != nil {
		return x.ChannelHash
	}
	return 0
}

func (x *PacketEvent) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

func (x *PacketEvent) GetTimeMs() int64 {
	if x != nil {
		return x.TimeMs
	}
	return 0
}

func (x *PacketEvent) GetReporterNodeNum() uint32 {
	if x != nil {
		return x.ReporterNodeNum
	}
	return 0
}

func (x *PacketEvent) GetRelayChannelIndex() int32 {
	if x != nil {
		return x.RelayChannelIndex
	}
	return 0
}

func (x *PacketEvent) GetHolders() []*ChannelHolder {
	if x != nil {
		return x.Holders
	}
	return nil
}

type ChannelHolder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeNum       uint32                 `protobuf:"varint,1,opt,name=node_num,json=nodeNum,proto3" json:"node_num,omitempty"`
	ChannelIndex  uint32                 `protobuf:"varint,2,opt,name=channel_index,json=channelIndex,proto3" json:"channel_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelHolder) Reset() {
	*x = ChannelHolder{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelHolder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelHolder) ProtoMessage() {}

func (x *ChannelHolder) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelHolder.ProtoReflect.Descriptor instead.
func (*ChannelHolder) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *ChannelHolder) GetNodeNum() uint32 {
	if x != nil {
		return x.NodeNum
	}
	return 0
}

func (x *ChannelHolder) GetChannelIndex() uint32 {
	if x != nil {
		return x.ChannelIndex
	}
	return 0
}

type NodeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeEvent) Reset() {
	*x = NodeEvent{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEvent) ProtoMessage() {}

func (x *NodeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEvent.ProtoReflect.Descriptor instead.
func (*NodeEvent) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *NodeEvent) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

// TextMessageEvent: a text message a radio's relay persona received or sent (messages.read).
type TextMessageEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RadioId        string                 `protobuf:"bytes,1,opt,name=radio_id,json=radioId,proto3" json:"radio_id,omitempty"`
	IdentityNodeId string                 `protobuf:"bytes,2,opt,name=identity_node_id,json=identityNodeId,proto3" json:"identity_node_id,omitempty"`
	From           uint32                 `protobuf:"varint,3,opt,name=from,proto3" json:"from,omitempty"`
	To             uint32                 `protobuf:"varint,4,opt,name=to,proto3" json:"to,omitempty"`
	Channel        uint32                 `protobuf:"varint,5,opt,name=channel,proto3" json:"channel,omitempty"` // channel index on the identity; 0 for DMs
	Direct         bool                   `protobuf:"varint,6,opt,name=direct,proto3" json:"direct,omitempty"`
	Text           string                 `protobuf:"bytes,7,opt,name=text,proto3" json:"text,omitempty"`
	PacketId       uint32                 `protobuf:"varint,8,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	TimeMs         int64                  `protobuf:"varint,9,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	Direction      string                 `protobuf:"bytes,10,opt,name=direction,proto3" json:"direction,omitempty"` // "in" or "out"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TextMessageEvent) Reset() {
	*x = TextMessageEvent{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextMessageEvent) ProtoMessage() {}

func (x *TextMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextMessageEvent.ProtoReflect.Descriptor instead.
func (*TextMessageEvent) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *TextMessageEvent) GetRadioId() string {
	if x != nil {
		return x.RadioId
	}
	return ""
}

func (x *TextMessageEvent) GetIdentityNodeId() string {
	if x != nil {
		return x.IdentityNodeId
	}
	return ""
}

func (x *TextMessageEvent) GetFrom() uint32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *TextMessageEvent) GetTo() uint32 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *TextMessageEvent) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *TextMessageEvent) GetDirect() bool {
	if x != nil {
		return x.Direct
	}
	return false
}

func (x *TextMessageEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextMessageEvent) GetPacketId() uint32 {
	if x != nil {
		return x.PacketId
	}
	return 0
}

func (x *TextMessageEvent) GetTimeMs() int64 {
	if x != nil {
		return x.TimeMs
	}
	return 0
}

func (x *TextMessageEvent) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type TracerouteEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RadioId        string                 `protobuf:"bytes,1,opt,name=radio_id,json=radioId,proto3" json:"radio_id,omitempty"`
	IdentityNodeId string                 `protobuf:"bytes,2,opt,name=identity_node_id,json=identityNodeId,proto3" json:"identity_node_id,omitempty"`
	TargetNodeId   string                 `protobuf:"bytes,3,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	Route          []string               `protobuf:"bytes,4,rep,name=route,proto3" json:"route,omitempty"`
	SnrTowards     []float64              `protobuf:"fixed64,5,rep,packed,name=snr_towards,json=snrTowards,proto3" json:"snr_towards,omitempty"`
	RouteBack      []string               `protobuf:"bytes,6,rep,name=route_back,json=routeBack,proto3" json:"route_back,omitempty"`
	SnrBack        []float64              `protobuf:"fixed64,7,rep,packed,name=snr_back,json=snrBack,proto3" json:"snr_back,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TracerouteEvent) Reset() {
	*x = TracerouteEvent{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracerouteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracerouteEvent) ProtoMessage() {}

func (x *TracerouteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracerouteEvent.ProtoReflect.Descriptor instead.
func (*TracerouteEvent) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *TracerouteEvent) GetRadioId() string {
	if x != nil {
		return x.RadioId
	}
	return ""
}

func (x *TracerouteEvent) GetIdentityNodeId() string {
	if x != nil {
		return x.IdentityNodeId
	}
	return ""
}

func (x *TracerouteEvent) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *TracerouteEvent) GetRoute() []string {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *TracerouteEvent) GetSnrTowards() []float64 {
	if x != nil {
		return x.SnrTowards
	}
	return nil
}

func (x *TracerouteEvent) GetRouteBack() []string {
	if x != nil {
		return x.RouteBack
	}
	return nil
}

func (x *TracerouteEvent) GetSnrBack() []float64 {
	if x != nil {
		return x.SnrBack
	}
	return nil
}

type ListRadiosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRadiosRequest) Reset() {
	*x = ListRadiosRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRadiosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRadiosRequest) ProtoMessage() {}

func (x *ListRadiosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRadiosRequest.ProtoReflect.Descriptor instead.
func (*ListRadiosRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{23}
}

type ListRadiosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Radios        []*Radio               `protobuf:"bytes,1,rep,name=radios,proto3" json:"radios,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRadiosResponse) Reset() {
	*x = ListRadiosResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRadiosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRadiosResponse) ProtoMessage() {}

func (x *ListRadiosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRadiosResponse.ProtoReflect.Descriptor instead.
func (*ListRadiosResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *ListRadiosResponse) GetRadios() []*Radio {
	if x != nil {
		return x.Radios
	}
	return nil
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RadioId       string                 `protobuf:"bytes,1,opt,name=radio_id,json=radioId,proto3" json:"radio_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *ListNodesRequest) GetRadioId() string {
	if x != nil {
		return x.RadioId
	}
	return ""
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *ListNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type SendTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RadioId       string                 `protobuf:"bytes,1,opt,name=radio_id,json=radioId,proto3" json:"radio_id,omitempty"` // "" = the main radio
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`                          // "!a1c40e07" for a DM, "" for a channel
	Channel       uint32                 `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`               // channel index on the relay persona
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	WantAck       bool                   `protobuf:"varint,5,opt,name=want_ack,json=wantAck,proto3" json:"want_ack,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTextRequest) Reset() {
	*x = SendTextRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTextRequest) ProtoMessage() {}

func (x *SendTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTextRequest.ProtoReflect.Descriptor instead.
func (*SendTextRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *SendTextRequest) GetRadioId() string {
	if x != nil {
		return x.RadioId
	}
	return ""
}

func (x *SendTextRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendTextRequest) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *SendTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendTextRequest) GetWantAck() bool {
	if x != nil {
		return x.WantAck
	}
	return false
}

type TracerouteRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	RadioId string                 `protobuf:"bytes,1,opt,name=radio_id,json=radioId,proto3" json:"radio_id,omitempty"` // "" = the main radio
	Target  string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`                  // "!a1c40e07"
	// "" = the chosen identity (or the relay persona). Anything else must be that identity.
	From          string `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TracerouteRequest) Reset() {
	*x = TracerouteRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracerouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracerouteRequest) ProtoMessage() {}

func (x *TracerouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracerouteRequest.ProtoReflect.Descriptor instead.
func (*TracerouteRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *TracerouteRequest) GetRadioId() string {
	if x != nil {
		return x.RadioId
	}
	return ""
}

func (x *TracerouteRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *TracerouteRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type SendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PacketId      uint32                 `protobuf:"varint,1,opt,name=packet_id,json=packetId,proto3" json:"packet_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponse) Reset() {
	*x = SendResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponse) ProtoMessage() {}

func (x *SendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponse.ProtoReflect.Descriptor instead.
func (*SendResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{29}
}

func (x *SendResponse) GetPacketId() uint32 {
	if x != nil {
		return x.PacketId
	}
	return 0
}

type ListSensorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSensorsRequest) Reset() {
	*x = ListSensorsRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSensorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSensorsRequest) ProtoMessage() {}

func (x *ListSensorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSensorsRequest.ProtoReflect.Descriptor instead.
func (*ListSensorsRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{30}
}

type ListSensorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sensors       []*Sensor              `protobuf:"bytes,1,rep,name=sensors,proto3" json:"sensors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSensorsResponse) Reset() {
	*x = ListSensorsResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSensorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSensorsResponse) ProtoMessage() {}

func (x *ListSensorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSensorsResponse.ProtoReflect.Descriptor instead.
func (*ListSensorsResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{31}
}

func (x *ListSensorsResponse) GetSensors() []*Sensor {
	if x != nil {
		return x.Sensors
	}
	return nil
}

// Sensor is one of the host's sensors. A plugin may publish to those whose kind is "push".
type Sensor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`                                                                                 // push | exec | file
	Fields        map[string]float64     `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"` // its latest reading, field name to value
	ReadAtUnix    int64                  `protobuf:"varint,5,opt,name=read_at_unix,json=readAtUnix,proto3" json:"read_at_unix,omitempty"`                                                // when that reading was taken (0 = never read)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sensor) Reset() {
	*x = Sensor{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sensor) ProtoMessage() {}

func (x *Sensor) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sensor.ProtoReflect.Descriptor instead.
func (*Sensor) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{32}
}

func (x *Sensor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Sensor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Sensor) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Sensor) GetFields() map[string]float64 {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *Sensor) GetReadAtUnix() int64 {
	if x != nil {
		return x.ReadAtUnix
	}
	return 0
}

type PublishSensorRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SensorId string                 `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"` // the id of a sensor whose kind is "push"
	// fields are Meshtastic names: temperature, humidity, lux, voltage, current, pm10, pm25, pm100,
	// distance, radiation, rainfall_1h, rainfall_24h (docs/sensors.md). Unknown names are ignored.
	Fields        map[string]float64 `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishSensorRequest) Reset() {
	*x = PublishSensorRequest{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishSensorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishSensorRequest) ProtoMessage() {}

func (x *PublishSensorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishSensorRequest.ProtoReflect.Descriptor instead.
func (*PublishSensorRequest) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{33}
}

func (x *PublishSensorRequest) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *PublishSensorRequest) GetFields() map[string]float64 {
	if x != nil {
		return x.Fields
	}
	return nil
}

type PublishSensorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishSensorResponse) Reset() {
	*x = PublishSensorResponse{}
	mi := &file_plugin_v1_plugin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishSensorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishSensorResponse) ProtoMessage() {}

func (x *PublishSensorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_v1_plugin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishSensorResponse.ProtoReflect.Descriptor instead.
func (*PublishSensorResponse) Descriptor() ([]byte, []int) {
	return file_plugin_v1_plugin_proto_rawDescGZIP(), []int{34}
}

var File_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x16plugin/v1/plugin.proto\x12\x18repeatertastic.plugin.v1\"\xc4\x02\n" +
	"\rPluginMessage\x127\n" +
	"\x05hello\x18\x01 \x01(\v2\x1f.repeatertastic.plugin.v1.HelloH\x00R\x05hello\x12:\n" +
	"\x06status\x18\x02 \x01(\v2 .repeatertastic.plugin.v1.StatusH\x00R\x06status\x125\n" +
	"\x03log\x18\x03 \x01(\v2!.repeatertastic.plugin.v1.LogLineH\x00R\x03log\x12C\n" +
	"\theartbeat\x18\x04 \x01(\v2#.repeatertastic.plugin.v1.HeartbeatH\x00R\theartbeat\x12;\n" +
	"\x05panel\x18\x05 \x01(\v2#.repeatertastic.plugin.v1.PanelDataH\x00R\x05panelB\x05\n" +
	"\x03msg\"\xea\x04\n" +
	"\vHostMessage\x12=\n" +
	"\awelcome\x18\x01 \x01(\v2!.repeatertastic.plugin.v1.WelcomeH\x00R\awelcome\x12?\n" +
	"\x06packet\x18\x02 \x01(\v2%.repeatertastic.plugin.v1.PacketEventH\x00R\x06packet\x129\n" +
	"\x04node\x18\x03 \x01(\v2#.repeatertastic.plugin.v1.NodeEventH\x00R\x04node\x12@\n" +
	"\x04text\x18\x04 \x01(\v2*.repeatertastic.plugin.v1.TextMessageEventH\x00R\x04text\x12K\n" +
	"\n" +
	"traceroute\x18\x05 \x01(\v2).repeatertastic.plugin.v1.TracerouteEventH\x00R\n" +
	"traceroute\x12G\n" +
	"\bsettings\x18\x06 \x01(\v2).repeatertastic.plugin.v1.SettingsChangedH\x00R\bsettings\x124\n" +
	"\x04stop\x18\a \x01(\v2\x1e.repeatertastic.plugin.v1.StopH\x00R\x04stop\x12?\n" +
	"\x06action\x18\b \x01(\v2%.repeatertastic.plugin.v1.PanelActionH\x00R\x06action\x12J\n" +
	"\fstatus_event\x18\t \x01(\v2%.repeatertastic.plugin.v1.StatusEventH\x00R\vstatusEventB\x05\n" +
	"\x03msg\"\x91\x01\n" +
	"\x05Hello\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\rR\n" +
	"apiVersion\x12%\n" +
	"\x0eplugin_version\x18\x03 \x01(\tR\rpluginVersion\x12#\n" +
	"\rmanifest_yaml\x18\x04 \x01(\tR\fmanifestYaml\"\xe8\x01\n" +
	"\aWelcome\x12\x1f\n" +
	"\vapi_version\x18\x01 \x01(\rR\n" +
	"apiVersion\x12!\n" +
	"\fhost_version\x18\x02 \x01(\tR\vhostVersion\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissions\x12#\n" +
	"\rsettings_json\x18\x04 \x01(\tR\fsettingsJson\x127\n" +
	"\x06radios\x18\x05 \x03(\v2\x1f.repeatertastic.plugin.v1.RadioR\x06radios\x12\x19\n" +
	"\bdata_dir\x18\x06 \x01(\tR\adataDir\"\xb9\x01\n" +
	"\x06Status\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\x12D\n" +
	"\x06fields\x18\x02 \x03(\v2,.repeatertastic.plugin.v1.Status.FieldsEntryR\x06fields\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\aLogLine\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\v\n" +
	"\tHeartbeat\"\x1f\n" +
	"\tPanelData\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\"D\n" +
	"\vPanelAction\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\tR\vpayloadJson\"6\n" +
	"\x0fSettingsChanged\x12#\n" +
	"\rsettings_json\x18\x01 \x01(\tR\fsettingsJson\"\x1e\n" +
	"\x04Stop\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xbd\x02\n" +
	"\x05Radio\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x16\n" +
	"\x06preset\x18\x04 \x01(\tR\x06preset\x12\x1f\n" +
	"\vpreset_name\x18\x05 \x01(\tR\n" +
	"presetName\x12#\n" +
	"\rfrequency_mhz\x18\x06 \x01(\x01R\ffrequencyMhz\x12\x1c\n" +
	"\tconnected\x18\a \x01(\bR\tconnected\x128\n" +
	"\x05relay\x18\b \x01(\v2\".repeatertastic.plugin.v1.IdentityR\x05relay\x12B\n" +
	"\n" +
	"identities\x18\t \x03(\v2\".repeatertastic.plugin.v1.IdentityR\n" +
	"identities\"\xa3\x04\n" +
	"\vRadioStatus\x12\x19\n" +
	"\bradio_id\x18\x01 \x01(\tR\aradioId\x12\x1c\n" +
	"\tconnected\x18\x02 \x01(\bR\tconnected\x12&\n" +
	"\x0fnoise_floor_dbm\x18\x03 \x01(\x05R\rnoiseFloorDbm\x12$\n" +
	"\x0eairtime_tx_pct\x18\x04 \x01(\x01R\fairtimeTxPct\x12$\n" +
	"\x0eduty_limit_pct\x18\x05 \x01(\x01R\fdutyLimitPct\x12(\n" +
	"\x10channel_util_pct\x18\x06 \x01(\x01R\x0echannelUtilPct\x12\x14\n" +
	"\x05queue\x18\a \x01(\rR\x05queue\x12\x0e\n" +
	"\x02rx\x18\b \x01(\x04R\x02rx\x12\x0e\n" +
	"\x02tx\x18\t \x01(\x04R\x02tx\x12\x17\n" +
	"\arx_dupe\x18\n" +
	" \x01(\x04R\x06rxDupe\x12)\n" +
	"\x10rx_undecryptable\x18\v \x01(\x04R\x0frxUndecryptable\x12\x15\n" +
	"\x06rx_bad\x18\f \x01(\x04R\x05rxBad\x12\x1b\n" +
	"\ttx_failed\x18\r \x01(\x04R\btxFailed\x12\x15\n" +
	"\x06ack_ok\x18\x0e \x01(\x04R\x05ackOk\x12\x19\n" +
	"\back_fail\x18\x0f \x01(\x04R\aackFail\x12!\n" +
	"\fdropped_duty\x18\x10 \x01(\x04R\vdroppedDuty\x12\x19\n" +
	"\buptime_s\x18\x11 \x01(\x03R\auptimeS\x12\x1f\n" +
	"\vnodes_heard\x18\x12 \x01(\rR\n" +
	"nodesHeard\"-\n" +
	"\x10GetStatusRequest\x12\x19\n" +
	"\bradio_id\x18\x01 \x01(\tR\aradioId\"R\n" +
	"\x11GetStatusResponse\x12=\n" +
	"\x06radios\x18\x01 \x03(\v2%.repeatertastic.plugin.v1.RadioStatusR\x06radios\"L\n" +
	"\vStatusEvent\x12=\n" +
	"\x06radios\x18\x01 \x03(\v2%.repeatertastic.plugin.v1.RadioStatusR\x06radios\"\x95\x01\n" +
	"\bIdentity\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bnode_num\x18\x02 \x01(\rR\anodeNum\x12\x1b\n" +
	"\tlong_name\x18\x03 \x01(\tR\blongName\x12\x1d\n" +
	"\n" +
	"short_name\x18\x04 \x01(\tR\tshortName\x12\x19\n" +
	"\bradio_id\x18\x05 \x01(\tR\aradioId\"\xc4\x02\n" +
	"\x04Node\x12\x19\n" +
	"\bnode_num\x18\x01 \x01(\rR\anodeNum\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bradio_id\x18\x03 \x01(\tR\aradioId\x12\x12\n" +
	"\x04user\x18\x04 \x01(\fR\x04user\x12\x1a\n" +
	"\bposition\x18\x05 \x01(\fR\bposition\x12%\n" +
	"\x0edevice_metrics\x18\x06 \x01(\fR\rdeviceMetrics\x12\"\n" +
	"\rlast_heard_ms\x18\a \x01(\x03R\vlastHeardMs\x12\x10\n" +
	"\x03snr\x18\b \x01(\x02R\x03snr\x12\x12\n" +
	"\x04rssi\x18\t \x01(\x05R\x04rssi\x12\x1b\n" +
	"\thops_away\x18\n" +
	" \x01(\x05R\bhopsAway\x12\x19\n" +
	"\bvia_mqtt\x18\v \x01(\bR\aviaMqtt\x12\x14\n" +
	"\x05local\x18\f \x01(\bR\x05local\"\x93\x03\n" +
	"\vPacketEvent\x12\x19\n" +
	"\bradio_id\x18\x01 \x01(\tR\aradioId\x12\x1c\n" +
	"\tdirection\x18\x02 \x01(\tR\tdirection\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1f\n" +
	"\vmesh_packet\x18\x04 \x01(\fR\n" +
	"meshPacket\x12\x18\n" +
	"\adecoded\x18\x05 \x01(\bR\adecoded\x12!\n" +
	"\fchannel_hash\x18\x06 \x01(\rR\vchannelHash\x12!\n" +
	"\fchannel_name\x18\a \x01(\tR\vchannelName\x12\x17\n" +
	"\atime_ms\x18\b \x01(\x03R\x06timeMs\x12*\n" +
	"\x11reporter_node_num\x18\t \x01(\rR\x0freporterNodeNum\x12.\n" +
	"\x13relay_channel_index\x18\n" +
	" \x01(\x05R\x11relayChannelIndex\x12A\n" +
	"\aholders\x18\v \x03(\v2'.repeatertastic.plugin.v1.ChannelHolderR\aholders\"O\n" +
	"\rChannelHolder\x12\x19\n" +
	"\bnode_num\x18\x01 \x01(\rR\anodeNum\x12#\n" +
	"\rchannel_index\x18\x02 \x01(\rR\fchannelIndex\"?\n" +
	"\tNodeEvent\x122\n" +
	"\x04node\x18\x01 \x01(\v2\x1e.repeatertastic.plugin.v1.NodeR\x04node\"\x95\x02\n" +
	"\x10TextMessageEvent\x12\x19\n" +
	"\bradio_id\x18\x01 \x01(\tR\aradioId\x12(\n" +
	"\x10identity_node_id\x18\x02 \x01(\tR\x0eidentityNodeId\x12\x12\n" +
	"\x04from\x18\x03 \x01(\rR\x04from\x12\x0e\n" +
	"\x02to\x18\x04 \x01(\rR\x02to\x12\x18\n" +
	"\achannel\x18\x05 \x01(\rR\achannel\x12\x16\n" +
	"\x06direct\x18\x06 \x01(\bR\x06direct\x12\x12\n" +
	"\x04text\x18\a \x01(\tR\x04text\x12\x1b\n" +
	"\tpacket_id\x18\b \x01(\rR\bpacketId\x12\x17\n" +
	"\atime_ms\x18\t \x01(\x03R\x06timeMs\x12\x1c\n" +
	"\tdirection\x18\n" +
	" \x01(\tR\tdirection\"\xed\x01\n" +
	"\x0fTracerouteEvent\x12\x19\n" +
	"\bradio_id\x18\x01 \x01(\tR\aradioId\x12(\n" +
	"\x10identity_node_id\x18\x02 \x01(\tR\x0eidentityNodeId\x12$\n" +
	"\x0etarget_node_id\x18\x03 \x01(\tR\ftargetNodeId\x12\x14\n" +
	"\x05route\x18\x04 \x03(\tR\x05route\x12\x1f\n" +
	"\vsnr_towards\x18\x05 \x03(\x01R\n" +
	"snrTowards\x12\x1d\n" +
	"\n" +
	"route_back\x18\x06 \x03(\tR\trouteBack\x12\x19\n" +
	"\bsnr_back\x18\a \x03(\x01R\asnrBack\"\x13\n" +
	"\x11ListRadiosRequest\"M\n" +
	"\x12ListRadiosResponse\x127\n" +
	"\x06radios\x18\x01 \x03(\v2\x1f.repeatertastic.plugin.v1.RadioR\x06radios\"-\n" +
	"\x10ListNodesRequest\x12\x19\n" +
	"\bradio_id\x18\x01 \x01(\tR\aradioId\"I\n" +
	"\x11ListNodesResponse\x124\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1e.repeatertastic.plugin.v1.NodeR\x05nodes\"\x85\x01\n" +
	"\x0fSendTextRequest\x12\x19\n" +
	"\bradio_id\x18\x01 \x01(\tR\aradioId\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x18\n" +
	"\achannel\x18\x03 \x01(\rR\achannel\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x19\n" +
	"\bwant_ack\x18\x05 \x01(\bR\awantAck\"Z\n" +
	"\x11TracerouteRequest\x12\x19\n" +
	"\bradio_id\x18\x01 \x01(\tR\aradioId\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\"+\n" +
	"\fSendResponse\x12\x1b\n" +
	"\tpacket_id\x18\x01 \x01(\rR\bpacketId\"\x14\n" +
	"\x12ListSensorsRequest\"Q\n" +
	"\x13ListSensorsResponse\x12:\n" +
	"\asensors\x18\x01 \x03(\v2 .repeatertastic.plugin.v1.SensorR\asensors\"\xe3\x01\n" +
	"\x06Sensor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12D\n" +
	"\x06fields\x18\x04 \x03(\v2,.repeatertastic.plugin.v1.Sensor.FieldsEntryR\x06fields\x12 \n" +
	"\fread_at_unix\x18\x05 \x01(\x03R\n" +
	"readAtUnix\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xc2\x01\n" +
	"\x14PublishSensorRequest\x12\x1b\n" +
	"\tsensor_id\x18\x01 \x01(\tR\bsensorId\x12R\n" +
	"\x06fields\x18\x02 \x03(\v2:.repeatertastic.plugin.v1.PublishSensorRequest.FieldsEntryR\x06fields\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\x17\n" +
	"\x15PublishSensorResponse2\xc0\x06\n" +
	"\n" +
	"PluginHost\x12]\n" +
	"\aSession\x12'.repeatertastic.plugin.v1.PluginMessage\x1a%.repeatertastic.plugin.v1.HostMessage(\x010\x01\x12g\n" +
	"\n" +
	"ListRadios\x12+.repeatertastic.plugin.v1.ListRadiosRequest\x1a,.repeatertastic.plugin.v1.ListRadiosResponse\x12d\n" +
	"\tListNodes\x12*.repeatertastic.plugin.v1.ListNodesRequest\x1a+.repeatertastic.plugin.v1.ListNodesResponse\x12]\n" +
	"\bSendText\x12).repeatertastic.plugin.v1.SendTextRequest\x1a&.repeatertastic.plugin.v1.SendResponse\x12a\n" +
	"\n" +
	"Traceroute\x12+.repeatertastic.plugin.v1.TracerouteRequest\x1a&.repeatertastic.plugin.v1.SendResponse\x12j\n" +
	"\vListSensors\x12,.repeatertastic.plugin.v1.ListSensorsRequest\x1a-.repeatertastic.plugin.v1.ListSensorsResponse\x12p\n" +
	"\rPublishSensor\x12..repeatertastic.plugin.v1.PublishSensorRequest\x1a/.repeatertastic.plugin.v1.PublishSensorResponse\x12d\n" +
	"\tGetStatus\x12*.repeatertastic.plugin.v1.GetStatusRequest\x1a+.repeatertastic.plugin.v1.GetStatusResponseB;Z9github.com/ScotMesh/RepeaterTastic/api/plugin/v1;pluginv1b\x06proto3"

var (
	file_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_plugin_v1_plugin_proto_rawDescData []byte
)

func file_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_v1_plugin_proto_rawDesc), len(file_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_plugin_v1_plugin_proto_rawDescData
}

var file_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_plugin_v1_plugin_proto_goTypes = []any{
	(*PluginMessage)(nil),         // 0: repeatertastic.plugin.v1.PluginMessage
	(*HostMessage)(nil),           // 1: repeatertastic.plugin.v1.HostMessage
	(*Hello)(nil),                 // 2: repeatertastic.plugin.v1.Hello
	(*Welcome)(nil),               // 3: repeatertastic.plugin.v1.Welcome
	(*Status)(nil),                // 4: repeatertastic.plugin.v1.Status
	(*LogLine)(nil),               // 5: repeatertastic.plugin.v1.LogLine
	(*Heartbeat)(nil),             // 6: repeatertastic.plugin.v1.Heartbeat
	(*PanelData)(nil),             // 7: repeatertastic.plugin.v1.PanelData
	(*PanelAction)(nil),           // 8: repeatertastic.plugin.v1.PanelAction
	(*SettingsChanged)(nil),       // 9: repeatertastic.plugin.v1.SettingsChanged
	(*Stop)(nil),                  // 10: repeatertastic.plugin.v1.Stop
	(*Radio)(nil),                 // 11: repeatertastic.plugin.v1.Radio
	(*RadioStatus)(nil),           // 12: repeatertastic.plugin.v1.RadioStatus
	(*GetStatusRequest)(nil),      // 13: repeatertastic.plugin.v1.GetStatusRequest
	(*GetStatusResponse)(nil),     // 14: repeatertastic.plugin.v1.GetStatusResponse
	(*StatusEvent)(nil),           // 15: repeatertastic.plugin.v1.StatusEvent
	(*Identity)(nil),              // 16: repeatertastic.plugin.v1.Identity
	(*Node)(nil),                  // 17: repeatertastic.plugin.v1.Node
	(*PacketEvent)(nil),           // 18: repeatertastic.plugin.v1.PacketEvent
	(*ChannelHolder)(nil),         // 19: repeatertastic.plugin.v1.ChannelHolder
	(*NodeEvent)(nil),             // 20: repeatertastic.plugin.v1.NodeEvent
	(*TextMessageEvent)(nil),      // 21: repeatertastic.plugin.v1.TextMessageEvent
	(*TracerouteEvent)(nil),       // 22: repeatertastic.plugin.v1.TracerouteEvent
	(*ListRadiosRequest)(nil),     // 23: repeatertastic.plugin.v1.ListRadiosRequest
	(*ListRadiosResponse)(nil),    // 24: repeatertastic.plugin.v1.ListRadiosResponse
	(*ListNodesRequest)(nil),      // 25: repeatertastic.plugin.v1.ListNodesRequest
	(*ListNodesResponse)(nil),     // 26: repeatertastic.plugin.v1.ListNodesResponse
	(*SendTextRequest)(nil),       // 27: repeatertastic.plugin.v1.SendTextRequest
	(*TracerouteRequest)(nil),     // 28: repeatertastic.plugin.v1.TracerouteRequest
	(*SendResponse)(nil),          // 29: repeatertastic.plugin.v1.SendResponse
	(*ListSensorsRequest)(nil),    // 30: repeatertastic.plugin.v1.ListSensorsRequest
	(*ListSensorsResponse)(nil),   // 31: repeatertastic.plugin.v1.ListSensorsResponse
	(*Sensor)(nil),                // 32: repeatertastic.plugin.v1.Sensor
	(*PublishSensorRequest)(nil),  // 33: repeatertastic.plugin.v1.PublishSensorRequest
	(*PublishSensorResponse)(nil), // 34: repeatertastic.plugin.v1.PublishSensorResponse
	nil,                           // 35: repeatertastic.plugin.v1.Status.FieldsEntry
	nil,                           // 36: repeatertastic.plugin.v1.Sensor.FieldsEntry
	nil,                           // 37: repeatertastic.plugin.v1.PublishSensorRequest.FieldsEntry
}
var file_plugin_v1_plugin_proto_depIdxs = []int32{
	2,  // 0: repeatertastic.plugin.v1.PluginMessage.hello:type_name -> repeatertastic.plugin.v1.Hello
	4,  // 1: repeatertastic.plugin.v1.PluginMessage.status:type_name -> repeatertastic.plugin.v1.Status
	5,  // 2: repeatertastic.plugin.v1.PluginMessage.log:type_name -> repeatertastic.plugin.v1.LogLine
	6,  // 3: repeatertastic.plugin.v1.PluginMessage.heartbeat:type_name -> repeatertastic.plugin.v1.Heartbeat
	7,  // 4: repeatertastic.plugin.v1.PluginMessage.panel:type_name -> repeatertastic.plugin.v1.PanelData
	3,  // 5: repeatertastic.plugin.v1.HostMessage.welcome:type_name -> repeatertastic.plugin.v1.Welcome
	18, // 6: repeatertastic.plugin.v1.HostMessage.packet:type_name -> repeatertastic.plugin.v1.PacketEvent
	20, // 7: repeatertastic.plugin.v1.HostMessage.node:type_name -> repeatertastic.plugin.v1.NodeEvent
	21, // 8: repeatertastic.plugin.v1.HostMessage.text:type_name -> repeatertastic.plugin.v1.TextMessageEvent
	22, // 9: repeatertastic.plugin.v1.HostMessage.traceroute:type_name -> repeatertastic.plugin.v1.TracerouteEvent
	9,  // 10: repeatertastic.plugin.v1.HostMessage.settings:type_name -> repeatertastic.plugin.v1.SettingsChanged
	10, // 11: repeatertastic.plugin.v1.HostMessage.stop:type_name -> repeatertastic.plugin.v1.Stop
	8,  // 12: repeatertastic.plugin.v1.HostMessage.action:type_name -> repeatertastic.plugin.v1.PanelAction
	15, // 13: repeatertastic.plugin.v1.HostMessage.status_event:type_name -> repeatertastic.plugin.v1.StatusEvent
	11, // 14: repeatertastic.plugin.v1.Welcome.radios:type_name -> repeatertastic.plugin.v1.Radio
	35, // 15: repeatertastic.plugin.v1.Status.fields:type_name -> repeatertastic.plugin.v1.Status.FieldsEntry
	16, // 16: repeatertastic.plugin.v1.Radio.relay:type_name -> repeatertastic.plugin.v1.Identity
	16, // 17: repeatertastic.plugin.v1.Radio.identities:type_name -> repeatertastic.plugin.v1.Identity
	12, // 18: repeatertastic.plugin.v1.GetStatusResponse.radios:type_name -> repeatertastic.plugin.v1.RadioStatus
	12, // 19: repeatertastic.plugin.v1.StatusEvent.radios:type_name -> repeatertastic.plugin.v1.RadioStatus
	19, // 20: repeatertastic.plugin.v1.PacketEvent.holders:type_name -> repeatertastic.plugin.v1.ChannelHolder
	17, // 21: repeatertastic.plugin.v1.NodeEvent.node:type_name -> repeatertastic.plugin.v1.Node
	11, // 22: repeatertastic.plugin.v1.ListRadiosResponse.radios:type_name -> repeatertastic.plugin.v1.Radio
	17, // 23: repeatertastic.plugin.v1.ListNodesResponse.nodes:type_name -> repeatertastic.plugin.v1.Node
	32, // 24: repeatertastic.plugin.v1.ListSensorsResponse.sensors:type_name -> repeatertastic.plugin.v1.Sensor
	36, // 25: repeatertastic.plugin.v1.Sensor.fields:type_name -> repeatertastic.plugin.v1.Sensor.FieldsEntry
	37, // 26: repeatertastic.plugin.v1.PublishSensorRequest.fields:type_name -> repeatertastic.plugin.v1.PublishSensorRequest.FieldsEntry
	0,  // 27: repeatertastic.plugin.v1.PluginHost.Session:input_type -> repeatertastic.plugin.v1.PluginMessage
	23, // 28: repeatertastic.plugin.v1.PluginHost.ListRadios:input_type -> repeatertastic.plugin.v1.ListRadiosRequest
	25, // 29: repeatertastic.plugin.v1.PluginHost.ListNodes:input_type -> repeatertastic.plugin.v1.ListNodesRequest
	27, // 30: repeatertastic.plugin.v1.PluginHost.SendText:input_type -> repeatertastic.plugin.v1.SendTextRequest
	28, // 31: repeatertastic.plugin.v1.PluginHost.Traceroute:input_type -> repeatertastic.plugin.v1.TracerouteRequest
	30, // 32: repeatertastic.plugin.v1.PluginHost.ListSensors:input_type -> repeatertastic.plugin.v1.ListSensorsRequest
	33, // 33: repeatertastic.plugin.v1.PluginHost.PublishSensor:input_type -> repeatertastic.plugin.v1.PublishSensorRequest
	13, // 34: repeatertastic.plugin.v1.PluginHost.GetStatus:input_type -> repeatertastic.plugin.v1.GetStatusRequest
	1,  // 35: repeatertastic.plugin.v1.PluginHost.Session:output_type -> repeatertastic.plugin.v1.HostMessage
	24, // 36: repeatertastic.plugin.v1.PluginHost.ListRadios:output_type -> repeatertastic.plugin.v1.ListRadiosResponse
	26, // 37: repeatertastic.plugin.v1.PluginHost.ListNodes:output_type -> repeatertastic.plugin.v1.ListNodesResponse
	29, // 38: repeatertastic.plugin.v1.PluginHost.SendText:output_type -> repeatertastic.plugin.v1.SendResponse
	29, // 39: repeatertastic.plugin.v1.PluginHost.Traceroute:output_type -> repeatertastic.plugin.v1.SendResponse
	31, // 40: repeatertastic.plugin.v1.PluginHost.ListSensors:output_type -> repeatertastic.plugin.v1.ListSensorsResponse
	34, // 41: repeatertastic.plugin.v1.PluginHost.PublishSensor:output_type -> repeatertastic.plugin.v1.PublishSensorResponse
	14, // 42: repeatertastic.plugin.v1.PluginHost.GetStatus:output_type -> repeatertastic.plugin.v1.GetStatusResponse
	35, // [35:43] is the sub-list for method output_type
	27, // [27:35] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_plugin_v1_plugin_proto_init() }
func file_plugin_v1_plugin_proto_init() {
	if File_plugin_v1_plugin_proto != nil {
		return
	}
	file_plugin_v1_plugin_proto_msgTypes[0].OneofWrappers = []any{
		(*PluginMessage_Hello)(nil),
		(*PluginMessage_Status)(nil),
		(*PluginMessage_Log)(nil),
		(*PluginMessage_Heartbeat)(nil),
		(*PluginMessage_Panel)(nil),
	}
	file_plugin_v1_plugin_proto_msgTypes[1].OneofWrappers = []any{
		(*HostMessage_Welcome)(nil),
		(*HostMessage_Packet)(nil),
		(*HostMessage_Node)(nil),
		(*HostMessage_Text)(nil),
		(*HostMessage_Traceroute)(nil),
		(*HostMessage_Settings)(nil),
		(*HostMessage_Stop)(nil),
		(*HostMessage_Action)(nil),
		(*HostMessage_StatusEvent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_v1_plugin_proto_rawDesc), len(file_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_v1_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_plugin_v1_plugin_proto = out.File
	file_plugin_v1_plugin_proto_goTypes = nil
	file_plugin_v1_plugin_proto_depIdxs = nil
}
